name: talentpitch
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  flutter: 
    sdk: flutter

  # Get
  get: ^4.6.6
  get_storage: ^2.1.1

  loading_animation_widget: ^1.2.0+4
  cupertino_icons: ^1.0.6
  connectivity_plus: ^6.0.3
  intl: ^0.19.0
  permission_handler: ^11.0.0

dev_dependencies: 
  flutter_lints: 3.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
  - assets/icons/
  - assets/images/

