name: talentpitch
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  flutter: 
    sdk: flutter


  # Get
  get: ^4.6.6
  get_storage: ^2.1.1

  loading_animation_widget: ^1.2.0+4
  cupertino_icons: ^1.0.6
  connectivity_plus: ^6.0.3
  intl: ^0.18.1
  permission_handler: ^11.0.0

  # Firebase
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.4.3
  firebase_storage: ^11.0.14
  flutter_image_compress: ^2.2.0
  image_picker: ^1.1.0
  flutter_localization: ^0.1.14
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.9.0

dev_dependencies: 
  build_runner: ^2.4.9
  flutter_lints: 3.0.2
  flutter_test: 
    sdk: flutter
  json_serializable: ^6.8.0

flutter: 
  uses-material-design: true

  assets:
  - assets/icons/
  - assets/images/
  - .env

